# Generated by Django 5.2.17 on 2026-09-30 08:24

import django.db.models.deletion
import uuid
import vault.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('size_bytes', models.BigIntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ready', 'Ready'), ('deleted', 'Deleted')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ShareLink',
            fields=[
                ('id', models.CharField(default=vault.models.generate_link_token, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('mode', models.CharField(choices=[('timed', 'Timed'), ('one_time', 'One Time')], max_length=10)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('max_downloads', models.PositiveIntegerField(blank=True, null=True)),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('password_hash', models.CharField(blank=True, default='', max_length=256)),
                ('failed_attempts', models.PositiveSmallIntegerField(default=0)),
                ('locked_until', models.DateTimeField(blank=True, null=True)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('last_claimed_at', models.DateTimeField(blank=True, null=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('show_sender_email', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='link', to='vault.file')),
            ],
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('link_created', 'Link Created'), ('opened', 'Opened'), ('password_failed', 'Password Failed'), ('locked_out', 'Locked Out'), ('claimed', 'Claimed'), ('revoked', 'Revoked'), ('expired_cleanup', 'Expired Cleanup')], max_length=20)),
                ('ip_truncated', models.CharField(blank=True, default='', max_length=64)),
                ('user_agent', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('link', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='vault.sharelink')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddIndex(
            model_name='file',
            index=models.Index(fields=['owner', 'status'], name='vault_file_owner_i_0e9001_idx'),
        ),
        migrations.AddConstraint(
            model_name='sharelink',
            constraint=models.CheckConstraint(condition=models.Q(('mode', 'timed'), ('max_downloads__isnull', True), _connector='OR'), name='one_time_links_have_no_max_downloads'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['link', '-created_at'], name='vault_audit_link_id_2d66e0_idx'),
        ),
    ]
