# Generated by Django 5.2.17 on 2026-10-02 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vault', '0002_auditevent_audit_type_created_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='sharelink',
            name='lockout_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='reissue_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='reissue_expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sharelink',
            name='reissue_hash',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='auditevent',
            name='event_type',
            field=models.CharField(choices=[('link_created', 'Link Created'), ('opened', 'Opened'), ('password_failed', 'Password Failed'), ('locked_out', 'Locked Out'), ('claimed', 'Claimed'), ('revoked', 'Revoked'), ('auto_revoked', 'Auto Revoked'), ('reissued', 'Reissued'), ('expired_cleanup', 'Expired Cleanup')], max_length=20),
        ),
    ]
